filegroup(
    name = "read_vin_job",
    srcs = [
        "read_vin.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "servo_status_job",
    srcs = [
        "servo_status_did.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "vent_servo_status_job",
    srcs = [
        "vent_servo_status_did.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "gpio_mw_job",
    srcs = [
        "gpio_pin_did.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "temp_job",
    srcs = [
        "temp_did.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "start_rid",
    srcs = [
        "start_rid.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "hard_restart",
    srcs = [
        "hard_restart.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
