filegroup(
    name = "start_rid",
    srcs = [
        "start_rid.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "hard_restart",
    srcs = [
        "hard_restart.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "read_vin_job",
    srcs = [
        "read_vin.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)