filegroup(
    name = "service_someipy",
    srcs = [
        "service.json",
        ":datatype",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "datatype",
    srcs = [
        "sensor_read_data_type.json",
    ],
    visibility = ["//visibility:public"],
)