filegroup(
    name = "types_manifest",
    srcs = [
        "types_manifest.json",
        ":sensor_read_data_type",
        ":servo_data_type",
        ":sys_stat_data_type",
        ":radio_data_type",
        ":bme280_data_type",
        ":lsm6dox_data_type",
        ":gps_data_type",
        ":gps_rmc_data_type",
        ":gps_vtg_data_type",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sensor_read_data_type",
    srcs = ["sensor_read_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "servo_data_type",
    srcs = ["servo_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "sys_stat_data_type",
    srcs = ["sys_stat_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "radio_data_type",
    srcs = ["radio_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "bme280_data_type",
    srcs = ["bme280_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "lsm6dox_data_type",
    srcs = ["lsm6dox_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gps_data_type",
    srcs = ["gps_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gps_rmc_data_type",
    srcs = ["gps_rmc_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "gps_vtg_data_type",
    srcs = ["gps_vtg_data_type.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "all",
    srcs = [
        ":sensor_read_data_type",
        ":servo_data_type",
        ":sys_stat_data_type",
        ":radio_data_type",
        ":bme280_data_type",
        ":lsm6dox_data_type",
        ":gps_data_type",
        ":gps_rmc_data_type",
        ":gps_vtg_data_type",
    ],
    visibility = ["//visibility:public"],
)
