filegroup(
    name = "i2c_Write_job",
    srcs = [
        "i2c_Write_did.json",
        "@srp_platform//platform_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
