filegroup(
    name = "service_someipy",
    srcs = [
        "service.json",
        "gps_data_type.json",
        "gps_rmc_data_type.json",
        "gps_vtg_data_type.json",
    ],
    visibility = ["//visibility:public"],
)
