filegroup(
    name = "file_logger_job",
    srcs = [
        "file_logger_did.json",
        "@srp_platform//platform_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)