filegroup(
    name = "Example_dtc",
    srcs = [
        "example_dtc.json",
        "example_dtc_hex.json",
        "//deployment/system_definition/diag/jobs:read_vin_job",
    ],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "Incorrect_dtc_config",
    srcs = ["incorrect_dtc_config.json"],
    visibility = ["//visibility:public"],
)