
filegroup(
    name = "servo_status_job",
    srcs = [
        "servo_status_did.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "vent_servo_status_job",
    srcs = [
        "vent_servo_status_did.json",
        "//deployment/system_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)