
filegroup(
    name = "servo_status_job",
    srcs = [
        "servo_status_did.json",
        "@srp_platform//platform_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "vent_servo_status_job",
    srcs = [
        "vent_servo_status_did.json",
        "@srp_platform//platform_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "basic_servo_job",
    srcs = [
        "basic_did.json",
        "@srp_platform//platform_definition/diag/global:diag_dids",
    ],
    visibility = ["//visibility:public"],
)