filegroup(
    name = "dtc_com_data_structure",
    srcs = ["dtc_com_frame.json","dtc_event_com_frame.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "tinyNTP_com_data_structure",
    srcs = ["ntp_com_frame.json"],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "gpio_data_structure",
    srcs = ["gpio_com_frame.json"],
    visibility = ["//visibility:public"],
)
filegroup(
    name = "temp_data_structure",
    srcs = ["temp_sub_com_frame.json", "temp_read_com_frame.json"],
    visibility = ["//visibility:public"],
)