filegroup(
    name = "dtc_com_data_structure",
    srcs = ["dtc_com_frame.json","dtc_event_com_frame.json"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "tinyNTP_com_data_structure",
    srcs = ["ntp_com_frame.json"],
    visibility = ["//visibility:public"],
)