filegroup(
    name = "service_someipy",
    srcs = [
        "bme280_data_type.json",
        "lsm6dox_data_type.json",
        "service.json",
    ],
    visibility = ["//visibility:public"],
)
